"""Session-cookie authentication + single-use magic-link tokens.

Auth model:
  - User submits email at /login.
  - Emails ending in @test.test bypass the email step and log in instantly
    (development / demo seed accounts only — see seed.py).
  - All other emails get a one-click magic link sent via Resend.

Token security:
  - Tokens are signed with `itsdangerous` using SESSION_SECRET (15-min TTL).
  - Each token embeds the user's current `auth_nonce`. On successful sign-in
    we rotate the nonce — invalidating that token AND any other outstanding
    token for the same user. This is the single-use enforcement.
  - We never log full tokens or magic URLs (would be bearer credentials in
    application logs). Only the email + a short prefix is logged.
"""
from __future__ import annotations

import os
from typing import Optional

from fastapi import Depends, HTTPException, Request, status
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer
from sqlalchemy.orm import Session

from app.db import get_db
from app.models import Role, User, _new_nonce

MAGIC_LINK_TTL_SECONDS = 15 * 60  # 15 minutes
TEST_EMAIL_SUFFIX = "@test.test"


def is_dev_mode() -> bool:
    return os.environ.get("PROPERTYFLOW_DEV") == "1"


def is_test_email(email: str) -> bool:
    """Test-domain bypass is only honored in dev mode (PROPERTYFLOW_DEV=1).

    Even though `.test` is an IANA-reserved TLD that will never be a real
    domain, gating on the dev flag prevents accidental prod bypass if a
    @test.test user ever ends up in a production database."""
    return is_dev_mode() and email.strip().lower().endswith(TEST_EMAIL_SUFFIX)


def _serializer() -> URLSafeTimedSerializer:
    """Lazy: SESSION_SECRET may be generated by main.py at startup before
    any request comes in, but after this module is imported."""
    secret = os.environ.get("SESSION_SECRET")
    if not secret:
        # Should be unreachable: main.py validates at boot.
        raise RuntimeError("SESSION_SECRET is not set; cannot sign tokens")
    return URLSafeTimedSerializer(secret, salt="propertyflow-magic-link")


def make_magic_token(user: User) -> str:
    """Sign a token bound to the user's CURRENT auth_nonce."""
    return _serializer().dumps({"uid": user.id, "n": user.auth_nonce})


def consume_magic_token(db: Session, token: str) -> Optional[User]:
    """Validate a magic-link token, log the user in atomically, return them.

    Returns None if the token is invalid, expired, or has already been used
    (nonce mismatch). On success, rotates the user's nonce so this token —
    and any sibling tokens — can never be redeemed again.
    """
    try:
        data = _serializer().loads(token, max_age=MAGIC_LINK_TTL_SECONDS)
    except (BadSignature, SignatureExpired):
        return None
    if not isinstance(data, dict):
        return None
    uid = data.get("uid")
    nonce = data.get("n")
    if not isinstance(uid, int) or not isinstance(nonce, str):
        return None
    user = db.get(User, uid)
    if user is None or user.auth_nonce != nonce:
        return None
    # Single-use: rotate nonce so the token cannot be replayed.
    user.auth_nonce = _new_nonce()
    db.commit()
    return user


def login_user(request: Request, user: User) -> None:
    request.session["user_id"] = user.id


def logout_user(request: Request) -> None:
    request.session.pop("user_id", None)


def lookup_user(db: Session, email: str) -> Optional[User]:
    """Look up a user by email — case-insensitive. Returns None if unknown."""
    return db.query(User).filter(User.email.ilike(email.strip())).one_or_none()


# Backwards-compat alias used by older code.
authenticate_email = lookup_user


def current_user(request: Request, db: Session = Depends(get_db)) -> Optional[User]:
    """Optional dependency — None for anonymous requests."""
    uid = request.session.get("user_id")
    if not uid:
        return None
    return db.get(User, uid)


def require_user(user: Optional[User] = Depends(current_user)) -> User:
    """Dependency that enforces login (raises 401 if anonymous)."""
    if not user:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "login required")
    return user


def require_role(*allowed: Role):
    """Dependency factory: only allow users whose role is in `allowed`.

    Owner role passes every check (system-level)."""
    allowed_set = set(allowed)

    def _checker(user: User = Depends(require_user)) -> User:
        if user.role is Role.owner or user.role in allowed_set:
            return user
        raise HTTPException(status.HTTP_403_FORBIDDEN, "insufficient role")

    return _checker


def role_home(user: User) -> str:
    """Where to send a user after login."""
    if user.role is Role.owner:
        return "/owner"
    if user.role is Role.admin:
        return "/admin"
    return "/dashboard"
